#write a python function to capitalize each word in a file.
file1=open("text.txt","r")
list1=file1.read()
print("\nContents in 'text.txt'\n")
print(list1)
file1.close()
file2=open("newtxt.txt","w")
file2.write(list1.title())
file2.close()
file2=open("newtxt.txt","r")
list2=file2.read()
print("\nContents in 'newtxt.txt'\n")
print(list2)
file2.close()